export const lessons = [
{title:'The model and the system',goal:'Separate a learned model from the software that makes it useful.',paragraphs:[
'Imagine asking an assistant to summarize a document. You interact with one application, but several components cooperate. The interface accepts the file. Software extracts its text. A model processes a representation of that text. Other software formats the answer and may read it aloud. Calling all of this “the AI” is convenient, but it hides where each behavior comes from.',
'A learned model is a computation controlled by adjustable numbers called parameters. Training chooses those numbers using examples and an objective. During ordinary inference, the program uses the existing parameters to process a new input. A parameter is not a line of prose or a database row. Many parameters jointly influence an output, and a single fact need not occupy a single identifiable location.',
'The application surrounding the model can retrieve documents, run a calculator, enforce access rules, save conversation history, or call another model. If an assistant finds a newly published page, that does not prove its model was retrained. Retrieval can supply new information as part of the input. In the same way, a program can read a new configuration file without recompiling its core algorithm.',
'Trace this concrete request: “What does my installation guide say about setup?” First, the application searches the guide. Second, it inserts relevant passages into the model input alongside your question. Third, the model produces an answer. Fourth, the application displays the answer and source links. Search quality, model behavior, and source-link handling are separate things to test.',
'The key habit for this course is to ask: What is the input? What computation happens? What state changes? What evidence shows the output is useful? These questions work for language models, speech systems, and video restoration alike. Stop and describe the document assistant as a sequence of components before continuing.'
],question:'An assistant answers using a document uploaded a moment ago. What can you conclude?',options:['Its model parameters must have changed.','The application may have supplied the document during inference.','The model must have searched the internet.'],correct:1,explanation:'The document can be added to the model input without training. The answer alone does not establish that parameters changed or that internet search occurred.',prompt:'Explain the document assistant to another software engineer. Identify at least three components and where the document enters the process.',rubric:'Include input extraction or retrieval, model inference, and output presentation. Distinguish document context from learned parameters.'},
{title:'Training versus inference',goal:'Explain learning through a one-parameter model and inspect a training step.',paragraphs:[
'Start with a deliberately tiny predictor: output equals input multiplied by a weight. The weight is our only parameter. Suppose an example has input two and desired output six. With a weight of one, the model predicts two. Its prediction is four below the target. The job of training is to adjust the weight so that the prediction better matches the example.',
'A loss function measures the mismatch. For this lesson, use half of the squared error. First subtract the prediction from the target. Then square that difference and divide by two. With prediction two and target six, the error is four, and the loss is eight. Squaring makes both positive and negative errors contribute positively. The half is a mathematical convenience.',
'An optimizer provides a rule for changing the parameter. Our rule adds the learning rate times the input times the error to the current weight. With learning rate zero point one, input two, and error four, the weight increases by zero point eight. Its new value is one point eight. The new prediction is three point six, and the new loss is two point eight eight. The fit has improved.',
'Inference is different: choose an input and compute the output with the current weight. That operation does not by itself change the weight. In the experiment below, moving the slider chooses a weight manually. Pressing the training button applies the update rule. Each time the page displays a prediction, it is performing the toy equivalent of inference.',
'A lower training loss is not enough to establish usefulness. A model can fit the examples it saw and fail on new cases. We therefore separate training examples from evaluation examples. We also ask whether this model family can express the relationship at all. A predictor that only multiplies by a weight cannot represent every possible relationship. More data cannot automatically fix a badly chosen model.',
'Your experiment: reset the weight to one. Predict the first training result before pressing the button. Take several steps and describe what changes. Then set the weight to three and explain why the loss is zero on this example. Finally explain why one perfect example does not prove the model is reliable. No calculus is needed yet; later we will derive the update using a gradient.'
],question:'Which operation makes this example a training process?',options:['Displaying the prediction.','Changing the input.','Updating the weight using the prediction error.'],correct:2,explanation:'Training uses an objective and examples to update parameters. Computing an output with fixed parameters is inference. A user moving a slider is manually choosing a parameter, not executing the optimizer.',prompt:'Explain the first training step aloud, then write down the old weight, new weight, and why a separate evaluation set matters.',rubric:'Old weight 1; new weight 1.8; prediction changes from 2 to 3.6. Separate examples test whether improvement extends beyond the training data.',experiment:true},
{title:'How language becomes an answer',goal:'Describe tokens, context, and repeated next-token generation.',paragraphs:[
'A language model does not generally receive raw letters as the user sees them. A tokenizer converts text into a sequence of token identifiers. A token may represent a word, part of a word, punctuation, or another unit. Exact boundaries depend on the tokenizer. Token counts therefore do not equal word counts.',
'The model maps identifiers to numerical representations and processes them through layers. In transformer models, attention lets representations incorporate information from other allowed positions. A causal language model restricts access to future positions during next-token prediction. We will examine the matrix operations later; for now, understand that the computation uses relationships within the available context.',
'For an autoregressive language model, generating an answer is repeated prediction. Given the current context, the model assigns scores that can be converted to probabilities over possible next tokens. A decoding procedure selects a token, appends it to the sequence, and repeats. Selecting the highest-scoring token and sampling from a distribution are different procedures. Generation ends according to stopping rules or limits.',
'Consider the prefix “The kettle is”. Plausible continuations depend on context: boiling, empty, or broken might fit different documents. A likely continuation is not automatically a verified fact. The model is producing an output according to learned patterns and its current input. Checking whether a factual claim is true requires evidence beyond the fact that the sentence sounds natural.',
'Context is the input available for the current computation, including any conversation and retrieved material the application supplies. It has a finite limit. An application may omit, summarize, or retrieve older material when the conversation grows. Stored conversation history and the context actually sent to a model are therefore not necessarily identical.',
'Here is your Python refresher task. Read the short example below and predict its output before running it in any Python environment you already use. A dictionary stores token-like strings and scores. The max call chooses the key with the highest score. This illustrates one decoding decision; it does not implement tokenization, a transformer, or training. Expected output: boiling. If Python is not installed, the prediction and explanation are enough for this unit.'
],code:'scores = {"boiling": 0.6, "empty": 0.3, "broken": 0.1}\nchoice = max(scores, key=scores.get)\nprint(choice)',question:'Why can a fluent answer still contain a false statement?',options:['A plausible continuation is not the same as a verified claim.','Tokenization guarantees incorrect answers.','Language models cannot use supplied documents.'],correct:0,explanation:'Fluency and factual accuracy are different properties. Retrieved evidence can help, but the resulting answer still needs appropriate evaluation.',prompt:'Describe tokenization, model computation, and decoding as three separate stages. Then explain one reason an answer can be wrong.',rubric:'Text becomes token IDs; model computation produces scores using context and parameters; decoding selects the next token. Mention that plausibility does not guarantee factual support.'},
{title:'Data and evaluation',goal:'Recognize why provenance, leakage, and representative tests matter.',paragraphs:[
'Before training, someone must decide where examples come from and what they represent. A dataset is not just a pile of files. Its source, collection method, permissions, selection process, labels, and transformations affect what can be learned and how results should be interpreted. A model trained on one kind of recording may struggle with another.',
'Imagine collecting support questions from a product forum. You remove duplicates, exclude information you should not retain, document permitted uses, and separate training data from evaluation data. Publicly readable material is not automatically licensed for every use. The course will teach how to record provenance and investigate applicable permissions; a browser download alone does not answer those questions.',
'Leakage occurs when information that should be unavailable influences training or evaluation. Suppose almost identical support questions appear in both your training and test sets. The test may reward recognition of examples rather than the ability to handle new questions. Randomly splitting rows does not solve this if duplicates, related users, or neighboring video frames cross the split.',
'For video, neighboring frames can be extremely similar. If you train on one frame and test on its immediate neighbor, the result may overstate performance on a genuinely new video. Depending on the intended use, splitting by entire clip, scene, or source can create a more meaningful test. Always make the split reflect the future situation you care about.',
'A benchmark is a defined evaluation procedure, not a universal certificate of intelligence. Ask which inputs it includes, what the metric rewards, and what it omits. A voice interface might need word accuracy and response latency. A restoration system might need fidelity and temporal consistency. A document assistant might need supported answers and correct refusal when evidence is missing.',
'Try this audit: a team reports 98 percent accuracy after testing on 100 examples selected by the developer. Before comparing its model with another, ask what counts as correct, how examples were selected, whether they overlap training material, and whether independent users have different inputs. The number may be accurate for that test and still tell you little about your intended use.'
],question:'Why might splitting a video dataset by individual frames give misleading results?',options:['Video cannot be evaluated numerically.','Closely related frames may appear in both training and test sets.','Every test must use synthetic data.'],correct:1,explanation:'Related frames can leak scene-specific information across the split. Splitting at a suitable higher level, such as a video or scene, can better approximate new inputs.',prompt:'Design a test for a document assistant used by new customers. Name the data split, two things to measure, and one likely failure.',rubric:'Keep related or duplicate examples from crossing splits; test representative new customer questions; measure factual support and successful task completion, for example; include missing evidence or retrieval failure.'},
{title:'Video super-resolution',goal:'Distinguish video restoration from resizing and understand temporal information.',paragraphs:[
'Video super-resolution takes lower-resolution video and estimates a higher-resolution version. Its goal is usually restoration: producing detail consistent with the observed scene. Ordinary resizing can add pixels using interpolation, but adding pixels does not guarantee recovery of the original detail. Several different high-resolution scenes can produce similar low-resolution observations.',
'Video offers multiple views over time. A moving camera or object can reveal complementary information in neighboring frames. Using that information requires handling motion and changes in visibility. If the system combines observations from different locations without accounting for movement, details may blur or become inconsistent.',
'One influential framework, BasicVSR, organizes the problem around propagation, alignment, aggregation, and upsampling. Propagation carries information across frames. Alignment relates corresponding locations. Aggregation combines evidence. Upsampling produces the larger output. Different architectures implement these roles differently, so these names describe responsibilities rather than one mandatory algorithm.',
'Training often uses pairs of lower- and higher-resolution examples. Synthetic degradation can create a lower-resolution input from a cleaner source, but real camera blur, noise, and compression may differ from that simulation. A system that performs well on a particular synthetic test can struggle with real recordings. The assumed degradation is part of the problem definition.',
'A result can look sharp while containing invented detail. It can also look good as individual frames but shimmer when played as a video. Evaluate fidelity, perceived quality, temporal consistency, and runtime separately. If a source does not contain enough evidence to identify a tiny symbol, a plausible sharp output does not prove what that symbol originally was.',
'You do not need to inspect fine visual details to understand this field. We can use narrated comparisons, error summaries, controlled examples, and temporal measurements. Our future labs will explain what each measurement can and cannot establish. After this introduction, decide whether you want a broad overview or a deeper study of restoration models and their tradeoffs.'
],question:'A VSR output is sharper, but a small sign has changed between frames. What is the best conclusion?',options:['More pixels guarantee the sign is correct.','The model must be performing language-model training.','Sharpness alone has not established faithful, temporally consistent restoration.'],correct:2,explanation:'Sharpness, fidelity, and consistency over time are distinct qualities. A system can improve one while damaging another.',prompt:'Explain why multiple frames may help restoration, why motion matters, and why a sharper result may be misleading. Add whether you want to study VSR more deeply.',rubric:'Neighboring frames may provide complementary observations; motion requires correspondence handling; inferred detail can be plausible but unsupported. No visual inspection is required for this explanation.'},
{title:'Connect the pieces',goal:'Analyze a complete AI product and identify the right component to investigate.',paragraphs:[
'Consider a video research assistant. You upload a low-resolution clip, ask for a clearer version, and request a spoken explanation of the result. The interface uploads and decodes the file. A restoration model processes frames. Evaluation software records quality and timing information. A language model explains those measurements. A speech synthesizer reads the explanation. Storage and access controls support the workflow.',
'Each component has a different contract. The restoration model receives video-related tensors and produces restored frames. The language model receives text or other supported representations and produces an explanation. The speech synthesizer receives text and produces audio. An orchestrator connects these operations, passes data, handles failures, and decides when to return a result.',
'Training this system is not one single process. Its models may have been trained independently on different data with different objectives. Deploying them together does not automatically retrain them. During inference, hardware capacity, data transfer, model loading, and queueing can all affect the experience. A slow response does not necessarily mean the model computation itself is slow.',
'Now diagnose three failures. First, the restored clip flickers: investigate temporal behavior in restoration and the input conditions. Second, the spoken explanation claims the restoration is accurate without evidence: inspect the measurements supplied to the language model and how claims are checked. Third, the screen shows an answer quickly but audio starts much later: measure speech generation and playback separately.',
'For your unit project, write or dictate a walkthrough of either this video assistant or the document assistant from lesson one. Specify inputs, components, model parameters, runtime context, outputs, and evaluation. Include a failure scenario and the first measurement you would collect. You can use the template in the notes below; no paid tools or model downloads are required.',
'Your oral defense has three questions. What changes during training? What information can change at inference without retraining? What evidence would make you distrust a polished output? Answer without reading, then compare with the criteria. Return in a few days and repeat with a different example. If you can transfer the explanation, you are ready to move from the whole system into its individual mechanisms.'
],question:'The text answer is fast, but spoken playback starts much later. Where should you investigate first?',options:['Measure speech generation and playback stages separately.','Retrain the video model immediately.','Assume the tokenizer is the cause.'],correct:0,explanation:'Measure the stages associated with the delay before changing a model. End-to-end latency can come from orchestration, transfer, queues, generation, or playback.',prompt:'Project template: Input → components → model outputs → final output. Which parameters were learned? What runtime information is supplied? Name one failure, one measurement, and one test on an unfamiliar input.',rubric:'Describe at least three components and their inputs/outputs; distinguish fixed learned parameters from runtime context; choose a measurement relevant to the failure; explain why fluent speech or sharp imagery alone is insufficient. Completion is self-reviewed, not an AI-certified mastery score.'}
];
export function trainingResult(weight){const prediction=2*weight;return {prediction,loss:(6-prediction)**2/2};}
export function trainingStep(weight){return weight+0.1*2*(6-2*weight);}
