import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';

const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',error=>errors.push(error.message));
try{
  await page.goto('http://127.0.0.1:4173');
  await page.getByText('Local narrator is ready.',{exact:true}).waitFor({state:'attached'});
  await page.getByRole('button',{name:'Reading and audio settings',exact:true}).click();
  assert.equal(await page.locator('#engine').inputValue(),'local');
  assert.equal(await page.locator('#rate').inputValue(),'1.3');
  assert.equal(await page.locator('#voice option').count(),3);
  await page.locator('#voice').selectOption('claire');
  await page.getByRole('button',{name:'Preview voice',exact:true}).click();
  await page.getByRole('button',{name:'Close settings',exact:true}).click();
  await page.getByText('Reading practice material.',{exact:true}).waitFor({timeout:180000});
  await page.getByRole('button',{name:'Pause',exact:true}).click();
  await page.getByText('Paused. Select Resume to continue.',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Reading and audio settings',exact:true}).click();
  await page.locator('#rate').selectOption('1.25');
  await page.locator('#size').selectOption('36');
  await page.locator('#theme').selectOption('light');
  await mkdir('.service',{recursive:true});
  await page.screenshot({path:'.service/audio-settings.png'});
  await page.getByRole('button',{name:'Close settings',exact:true}).click();
  await page.getByRole('button',{name:'Resume',exact:true}).click();
  await page.getByRole('button',{name:'Stop',exact:true}).click();
  await page.getByText('Stopped. Read lesson resumes from this passage.',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Play lesson',exact:true}).click();
  await page.getByText('Reading passage 1 of 5.',{exact:true}).waitFor({timeout:180000});
  assert.equal(await page.locator('.passage.active').count(),1);
  await page.getByRole('button',{name:'Stop',exact:true}).click();
  await page.getByRole('button',{name:'Audio preparation',exact:true}).click();
  await page.getByRole('button',{name:'Prepare lesson audio',exact:true}).click();
  await page.getByRole('button',{name:'Cancel audio preparation',exact:true}).click();
  await page.getByRole('button',{name:'Close settings',exact:true}).click();
  await page.getByText('Audio preparation stopped. Completed segments remain saved.',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Lesson 2: Training versus inference',exact:true}).click();
  await page.locator('#notes').fill('Temporary browser verification note');
  await page.reload();
  assert.equal(await page.locator('#notes').inputValue(),'Temporary browser verification note');
  await page.locator('#notes').fill('');
  await page.getByRole('button',{name:'Reading and audio settings',exact:true}).click();
  await page.locator('#engine').selectOption('browser');
  assert.match(await page.locator('#voice-note').textContent(),/online services/);
  await page.locator('#engine').selectOption('local');
  await page.getByRole('button',{name:'Close settings',exact:true}).click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  assert.deepEqual(errors,[]);
  console.log('Real local playback, pause/resume/stop, lesson highlighting, settings, notes persistence, and fallback controls passed.');
}finally{await browser.close();}
