import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';

const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',error=>errors.push(error.message));
try{
  await page.goto('http://127.0.0.1:4173');
  await page.getByText('Local narrator is ready.',{exact:true}).waitFor({state:'attached'});
  await page.getByRole('button',{name:'Reading and audio settings',exact:true}).click();
  assert.equal(await page.locator('#engine').inputValue(),'local');
  assert.equal(await page.locator('#rate').inputValue(),'1.3');
  assert.equal(await page.locator('#voice option').count(),3);
  assert.equal(await page.locator('#lesson-guide').isVisible(),true);
  assert.match(await page.locator('#lesson-time').textContent(),/minutes/);
  assert.equal(await page.locator('#recall-kind').textContent(),'AUTHORED RECALL PROMPT');
  await page.locator('#voice').selectOption('claire');
  await page.getByRole('button',{name:'Preview voice',exact:true}).click();
  await page.getByRole('button',{name:'Close settings',exact:true}).click();
  await page.getByText('Reading practice material.',{exact:true}).waitFor({timeout:180000});
  await page.getByRole('button',{name:'Pause',exact:true}).click();
  await page.getByText('Paused. Select Resume to continue.',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Reading and audio settings',exact:true}).click();
  await page.locator('#rate').selectOption('1.25');
  await page.locator('#size').selectOption('36');
  await page.locator('#theme').selectOption('light');
  await mkdir('.service',{recursive:true});
  await page.screenshot({path:'.service/audio-settings.png'});
  await page.getByRole('button',{name:'Close settings',exact:true}).click();
  await page.getByRole('button',{name:'Resume',exact:true}).click();
  await page.getByRole('button',{name:'Stop',exact:true}).click();
  await page.getByText('Stopped. Read lesson resumes from this passage.',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Play lesson',exact:true}).click();
  await page.getByText('Reading passage 1 of 5.',{exact:true}).waitFor({timeout:180000});
  assert.equal(await page.locator('.passage.active').count(),1);
  await page.getByRole('button',{name:'Stop',exact:true}).click();
  await page.getByRole('button',{name:'Unit 9: Retrieval and application systems',exact:true}).click();
  await page.getByRole('link',{name:'Lesson 21: Retrieval, evidence, and grounded answers',exact:true}).click();
  await page.getByRole('button',{name:'Run lab',exact:true}).click();
  assert.match(await page.locator('#lab-trace-summary').textContent(),/Execution trace/);
  assert.match(await page.locator('#lab-evidence-note').textContent(),/bounded authored local fixture/);
  await page.locator('#lab-trace-details summary').click();
  assert.match(await page.locator('#lab-trace').textContent(),/Structured output/);
  await page.getByRole('button',{name:'Read lab result',exact:true}).click();
  await page.getByText('Reading practice material.',{exact:true}).waitFor({timeout:180000});
  assert.equal(await page.getByRole('button',{name:'Pause',exact:true}).isEnabled(),true);
  await page.locator('#lab-query').fill('Where do training examples come from?');
  await page.getByText('Lab input changed. Predict and run the updated scenario.',{exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Pause',exact:true}).isEnabled(),false);
  assert.equal(await page.evaluate(()=>CSS.highlights?.has('spoken-word')??false),false);
  await page.locator('#lab-scenario').selectOption('1');
  assert.equal(await page.locator('#lab-result').textContent(),'Choose a scenario, predict the result, then select Run lab.');
  assert.equal(await page.getByRole('button',{name:'Read lab result',exact:true}).isEnabled(),false);
  await page.getByRole('button',{name:'Audio preparation',exact:true}).click();
  await page.getByRole('button',{name:'Prepare lesson audio',exact:true}).click();
  await page.getByRole('button',{name:'Cancel audio preparation',exact:true}).click();
  await page.getByRole('button',{name:'Close settings',exact:true}).click();
  await page.getByText('Audio preparation stopped. Completed segments remain saved.',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Unit 1: Orientation and the complete system',exact:true}).click();
  await page.getByRole('link',{name:'Lesson 3: How language becomes an answer',exact:true}).click();
  assert.equal(await page.locator('#lesson-reading a').getAttribute('href'),'https://arxiv.org/abs/1510.00726');
  assert.equal(await page.locator('#lesson-reading a').innerText(),'Goldberg Primer, 2015 (author PDF)');
  await page.getByRole('link',{name:'Lesson 2: Training versus inference',exact:true}).click();
  await page.locator('#notes').fill('Temporary browser verification note');
  await page.reload();
  assert.equal(await page.locator('#notes').inputValue(),'Temporary browser verification note');
  await page.locator('#notes').fill('');
  await page.getByRole('button',{name:'Reading and audio settings',exact:true}).click();
  await page.locator('#engine').selectOption('browser');
  assert.match(await page.locator('#voice-note').textContent(),/online services/);
  await page.locator('#engine').selectOption('local');
  await page.getByRole('button',{name:'Close settings',exact:true}).click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  assert.deepEqual(errors,[]);
  console.log('Real local playback, pause/resume/stop, lesson highlighting, settings, notes persistence, and fallback controls passed.');
}finally{await browser.close();}
